const icons = {
	barometer: 'barometer.svg',
	beach: 'beach-sunset.svg',
	celsius: 'celsius.svg',
	clouds: 'clouds-and sun.svg',
	803: 'cloudy-2.svg',
	804: 'cloudy-2.svg',
	cloudy2: 'cloudy-night.svg',
	cloudy3: 'cloudy.svg',
	fahrenheit: 'fahrenheit-degrees.svg',
	fog1: 'fog-2.svg',
	fog2: 'fog.svg',
	hail: 'hail.svg',
	heavy: 'heavy-rain.svg',
	hot: 'hot.svg',
	humidity: 'humidity.svg',
	icicles: 'icicles.svg',
	meteorology1: 'meteorology-2.svg',
	meteorology2: 'meteorology.svg',
	moon1: 'moon-phase.svg',
	moon2: 'moon.svg',
	rain1: 'rain-(3).svg',
	rain2: 'rain-2.svg',
	rain3: 'rain.svg',
	rainbow: 'rainbow.svg',
	rainy: 'rainy.svg',
	sleet: 'sleet.svg',
	smartphone: 'smartphone.svg',
	smartwatch: 'smartwatch.svg',
	snow1: 'snow-2.svg',
	snow2: 'snow.svg',
	snowflake: 'snowflake.svg',
	storm: 'storm.svg',
	800: 'sun.svg',
	sunrise: 'sunrise.svg',
	sunset: 'sunset.svg',
	temperature1: 'temperature-2.svg',
	temperature2: 'temperature.svg',
	thunderstorm: 'thunderstorm.svg',
	tornado1: 'tornado-2.svg',
	tornado2: 'tornado.svg',
	umbrella: 'umbrella.svg',
	weather1: 'weather-(3).svg',
	weather2: 'weather-(4).svg',
	weather3: 'weather-(5).svg',
	weather4: 'weather-2.svg',
	weather5: 'weather-forecast.svg',
	weather6: 'weather-vane.svg',
	weather7: 'weather.svg',
	wind1: 'wind-2.svg',
	wind2: 'wind.svg',
	windsock: 'windsock.svg',
};

const genericIcons = {
	windy2: 'windy.svg',
	wind: 'wind.svg',
	// wind1: 'wind-sign.svg',
	sunset: 'sunset.svg',
	sunrise: 'sunrise.svg',
	storm4: 'storm-4.svg',
	snowy: 'snowy-2.svg',
	snowy1: 'snowy-1.svg',
	snowflake: 'snowflake.svg',
	501: 'rain.svg',
	lightning: 'lightning.svg',
	hurricane: 'hurricane.svg',
	humidity: 'humidity.svg',


	hail2: 'hail-2.svg',
	thermometer: 'thermometer-3.svg',
	thermometer2: 'thermometer-2.svg',
	foggy2: 'foggy.svg',
	fog: 'fog.svg',
	// thermometer: 'thermometer-1.svg',
	// thermometer: 'thermometer.svg',
	// barometer: 'barometer.svg',
};

const dayIcons = {
	temperature: 'temperature.svg',
	801: 'cloudy.svg',
	501: 'rain-1.svg',
	511: 'rain-3.svg',
	windy1: 'windy-1.svg',
	sun1: 'sun.svg',
	800: 'sun-1.svg',
	storm3: 'storm-5.svg',
	snow: 'snow.svg',
	storm1: 'storm-1.svg',
	hail4: 'hail.svg',
	foggy1: 'foggy-1.svg',
	804: 'cloudy-2.svg',
	803: 'cloud.svg',
	802: 'cloud.svg',
	502: 'storm.svg',
	503: 'storm.svg',

};

const nightIcons = {
	temperature: 'temperature-1.svg',
	502: 'storm.svg',
	503: 'storm.svg',
	804: 'cloudy-2.svg',
	803: 'cloud.svg',
	802: 'cloud.svg',
	511: 'rain-4.svg',
	full: 'full-moon.svg',
	hail: 'hail-1.svg',
	foggy: 'foggy-2.svg',
	windy: 'windy-2.svg',
	800: 'night.svg',
	801: 'cloudy-1.svg',
	half: 'half-moon-1.svg',
	half1: 'half-moon.svg',
	storm: 'storm-2.svg',
	snowy: 'snowy.svg',
	501: 'rain-2.svg',
	storm: 'storm-3.svg',
	windy: 'windy-2.svg',
};


export default { dayIcons, nightIcons, genericIcons };